name: visimil
version: '0.1' 
summary: Image recognition API
description: |
  Image recognition API

grade: devel
confinement: devmode

apps:
  visimil:
    command: wrappers/visimil
    daemon: simple
  nginx-wrap:
    command: wrappers/nginx-wrap
    daemon: simple

parts:
  visimil:
    source: .
    plugin: python
    python-version: python3
    requirements: requirements.txt
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/flask-app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/flask-app
  wrappers:
    plugin: dump
    source: snap/
  nginx-wrap:
    after: [wrappers]
    plugin: nginx
    source: .
    install: |
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf.default
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
      cp ./nginx.conf.snap.template $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
